FYP_WebApp/Models/ConfigurationRecord.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.Core.Mapping;
using System.Linq;
using System.Web;
using System.Web.Http.Routing.Constraints;
using Foolproof;

namespace FYP_WebApp.Models
{
    public class ConfigurationRecord
    {
        public int Id { get; set; }
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd H:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime Created { get; set; }
        [Required]
        [Display(Name = "Store Location Under X Metres")]
        public double StoreLocationAccuracy { get; set; }
        [Display(Name = "System wide Message of the Day")]
        public string MessageOfTheDayText { get; set; }

        //Email and SMTP
        [Display(Name = "Send Urgent Emails")]
        public bool SmtpSendUrgentEmails { get; set; }
        [RequiredIfTrue("SmtpSendUrgentEmails")]
        [Display(Name = "SMTP Server URL")]
        public string SmtpUrl { get; set; }
        [RequiredIfTrue("SmtpSendUrgentEmails")]
        [Display(Name = "SMTP Port")]
        public int? SmtpPort { get; set; }
        [RequiredIfTrue("SmtpSendUrgentEmails")]
        [Display(Name = "SMTP Email From")]
        [DataType(DataType.EmailAddress)]
        public string SmtpEmailFrom { get; set; }
        [RequiredIfTrue("SmtpSendUrgentEmails")]
        [Display(Name = "SMTP Sender Username")]
        public string SmtpSenderUsername { get; set; }
        [RequiredIfTrue("SmtpSendUrgentEmails")]
        [DataType(DataType.Password)]
        [Display(Name = "SMTP Sender Password")]
        public string SmtpSenderPassword { get; set; }
        [Display(Name = "Use SSL")]
        public bool SmtpShouldUseSsl { get; set; }

        //Google Maps
        [Display(Name = "Google Maps API Key")]
        public string MapsApiKey { get; set; }

    }
}

FYP_WebApp/Controllers/ConfigurationRecordController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FYP_WebApp.Common_Logic;
using FYP_WebApp.DataAccessLayer;
using FYP_WebApp.Models;
using FYP_WebApp.ServiceLayer;

namespace FYP_WebApp.Controllers
{
    public class ConfigurationRecordController : Controller
    {
        private readonly ConfigurationRecordService _configurationRecordService;

        public ConfigurationRecordController()
        {
            _configurationRecordService = new ConfigurationRecordService();
        }

        public ConfigurationRecordController(IConfigurationRecordRepository configRecordRepository)
        {
            _configurationRecordService = new ConfigurationRecordService(configRecordRepository);
        }

        [CustomAuth(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(_configurationRecordService.GetAll());
        }

        [CustomAuth(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            try
            {
                return View(_configurationRecordService.GetDetails(id));
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new { @Error = Errors.InvalidParameter, @Message = ex.Message });
            }
            catch (ConfigurationRecordNotFoundException ex)
            {
                return RedirectToAction("Error", "Error", new { @Error = Errors.EntityNotFound, @Message = ex.Message });
            }
        }

        [CustomAuth(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ConfigurationRecord configurationRecord)
        {
            if (ModelState.IsValid)
            {
                var result = _configurationRecordService.Create(configurationRecord);

                if (result.Success)
                {
                    return Redirect("Index");
                }
                else
                {
                    return View(configurationRecord);
                }
            }

            return View(configurationRecord);
        }

        [CustomAuth(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            try
            {
                return View(_configurationRecordService.GetDetails(id));
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new { @Error = Errors.InvalidParameter, @Message = ex.Message });
            }
            catch (ConfigurationRecordNotFoundException ex)
            {
                return RedirectToAction("Error", "Error", new { @Error = Errors.EntityNotFound, @Message = ex.Message });
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ConfigurationRecord configurationRecord)
        {
            if (ModelState.IsValid)
            {
                var result = _configurationRecordService.Edit(configurationRecord);

                if (result.Success)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(configurationRecord);
                }
            }

            return View(configurationRecord);
        }

        [CustomAuth(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            try
            {
                return View(_configurationRecordService.GetDetails(id));
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new { @Error = Errors.InvalidParameter, @Message = ex.Message });
            }
            catch (ConfigurationRecordNotFoundException ex)
            {
                return RedirectToAction("Error", "Error", new { @Error = Errors.EntityNotFound, @Message = ex.Message });
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ConfigurationRecord configurationRecord = _configurationRecordService.GetDetails(id);

            var result = _configurationRecordService.Delete(configurationRecord);

            if (result.Success)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Error", "Error", new { @Error = Errors.SystemError, @Message = "Unable to delete entity." });
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _configurationRecordService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FYP_WebApp/Views/ConfigurationRecord/Create.cshtml
@model FYP_WebApp.Models.ConfigurationRecord

@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="card mb-3 rounded shadow">
        <h5 class="card-header">Automatic Location Linking</h5>
        <div class="card-body">
            <p>
                <span class="fa fa-info-circle" style="color:dodgerblue; margin-left:5px; margin-right: 5px; margin-top: 5px;"></span>
                This value determines the distance in metres that the system will use to automatically attribute a GPS Report to a location.
                <br />
            </p>
            <div class="form-group">
                @Html.LabelFor(model => model.StoreLocationAccuracy, htmlAttributes: new { @class = "control-label col-md-10" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StoreLocationAccuracy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StoreLocationAccuracy, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <div class="card mb-3 rounded shadow">
        <h5 class="card-header">System MOTD</h5>
        <div class="card-body">
            <p>
                <span class="fa fa-info-circle" style="color:dodgerblue; margin-left:5px; margin-right: 5px; margin-top: 5px;"></span>
                If this field has a value it will be displayed in a banner every time a user visits the homepage.
                <br />
            </p>
            <div class="form-group">
                @Html.LabelFor(model => model.MessageOfTheDayText, htmlAttributes: new { @class = "control-label col-md-10" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MessageOfTheDayText, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MessageOfTheDayText, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <div class="card mb-3 rounded shadow">
        <h5 class="card-header">SMTP Configuration</h5>
        <div class="card-body">
            <p>
                <span class="fa fa-info-circle" style="color:dodgerblue; margin-left:5px; margin-right: 5px; margin-top: 5px;"></span>
                If the following checkbox is selected, the system will send an email to the appropriate manager when an urgent request is received.
                <br />
            </p>
            <div class="form-group">
                @Html.LabelFor(model => model.SmtpSendUrgentEmails, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    @Html.CheckBoxFor(model => model.SmtpSendUrgentEmails, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SmtpSendUrgentEmails, "", new { @class = "text-danger" })
                </div>
            </div>
            <hr />
            <div class="form-group">
                @Html.LabelFor(model => model.SmtpUrl, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SmtpUrl, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SmtpUrl, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SmtpPort, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SmtpPort, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SmtpPort, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SmtpEmailFrom, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SmtpEmailFrom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SmtpEmailFrom, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SmtpSenderUsername, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SmtpSenderUsername, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SmtpSenderUsername, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SmtpSenderPassword, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SmtpSenderPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SmtpSenderPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SmtpShouldUseSsl, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    @Html.CheckBoxFor(model => model.SmtpShouldUseSsl, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SmtpShouldUseSsl, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <div class="card mb-3 rounded shadow">
        <h5 class="card-header">Google Maps API</h5>
        <div class="card-body">
            <p>
                <span class="fa fa-info-circle" style="color:dodgerblue; margin-left:5px; margin-right: 5px; margin-top: 5px;"></span>
                The Google Maps API Key should be stored here.
                <br />
            </p>
            <div class="form-group">
                @Html.LabelFor(model => model.MapsApiKey, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MapsApiKey, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MapsApiKey, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <div class="card mb-3 rounded shadow">
        <h5 class="card-header">Actions</h5>
        <div class="card-body">
            <button type="submit" class="btn btn-success">
                <i class="fa fa-check"></i>
                Submit
            </button>
            <button type="reset" class="btn btn-warning">
                <i class="fa fa-sync"></i>
                Reset
            </button>
            <button class="btn btn-danger" onclick="location.href = '@Url.Action("Index", "ConfigurationRecord")';return false;">
                <i class="fa fa-times"></i>
                Cancel
            </button>
        </div>
    </div>
</div>
}

FYP_WebApp/Views/ConfigurationRecord/Delete.cshtml
@model FYP_WebApp.Models.ConfigurationRecord

@{
    ViewBag.Title = "Delete";
}

<div>
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Confirm Delete</h4>
        <p>Are you sure you want to delete this record? It cannot be recovered afterwards.</p>
        <p>You can press 'back' in your browser to cancel this action.</p>
        <hr>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions">
                <input type="submit" value="Delete" class="btn btn-danger"/>
            </div>
        }
    </div>
</div>

FYP_WebApp/Views/ConfigurationRecord/Details.cshtml
@model FYP_WebApp.Models.ConfigurationRecord

@{
    ViewBag.Title = "Details";
}

<div>
    <div class="card rounded shadow mb-3">
        <div class="card-body">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Created)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Created)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.StoreLocationAccuracy)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.StoreLocationAccuracy)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.MessageOfTheDayText)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.MessageOfTheDayText)
                </dd>
            </dl>
            <hr/>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.SmtpSendUrgentEmails)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SmtpSendUrgentEmails)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.SmtpUrl)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SmtpUrl)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.SmtpPort)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SmtpPort)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.SmtpEmailFrom)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SmtpEmailFrom)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.SmtpSenderUsername)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SmtpSenderUsername)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.SmtpSenderPassword)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SmtpSenderPassword)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.SmtpShouldUseSsl)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SmtpShouldUseSsl)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.MapsApiKey)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.MapsApiKey)
                </dd>
            </dl>
        </div>
    </div>
    <div class="card rounded shadow mb-3">
        <h5 class="card-header">Actions</h5>
        <div class="card-body">
            <button class="btn btn-primary" onclick="location.href = '@Url.Action("Index", "ConfigurationRecord")';return false;">
                <i class="fa fa-arrow-circle-left"></i>
                Back
            </button>
            <button class="btn btn-warning" onclick="location.href = '@Url.Action("Edit", "ConfigurationRecord", new {id = Model.Id})';return false;">
                <i class="fa fa-edit"></i>
                Edit
            </button>
            <button class="btn btn-danger" onclick="location.href = '@Url.Action("Delete", "ConfigurationRecord", new {id = Model.Id})';return false;">
                <i class="fa fa-trash"></i>
                Delete
            </button>
        </div>
    </div>
</div>

FYP_WebApp/Views/ConfigurationRecord/Edit.cshtml
@model FYP_WebApp.Models.ConfigurationRecord

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="card mb-3 rounded shadow">
            <h5 class="card-header">Automatic Location Linking</h5>
            <div class="card-body">
                <p>
                    <span class="fa fa-info-circle" style="color:dodgerblue; margin-left:5px; margin-right: 5px; margin-top: 5px;"></span>
                    This value determines the distance in metres that the system will use to automatically attribute a GPS Report to a location.
                    <br />
                </p>
                <div class="form-group">
                    @Html.LabelFor(model => model.StoreLocationAccuracy, htmlAttributes: new { @class = "control-label col-md-10" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.StoreLocationAccuracy, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StoreLocationAccuracy, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 rounded shadow">
            <h5 class="card-header">System MOTD</h5>
            <div class="card-body">
                <p>
                    <span class="fa fa-info-circle" style="color:dodgerblue; margin-left:5px; margin-right: 5px; margin-top: 5px;"></span>
                    If this field has a value it will be displayed in a banner every time a user visits the homepage.
                    <br />
                </p>
                <div class="form-group">
                    @Html.LabelFor(model => model.MessageOfTheDayText, htmlAttributes: new { @class = "control-label col-md-10" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MessageOfTheDayText, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MessageOfTheDayText, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 rounded shadow">
            <h5 class="card-header">SMTP Configuration</h5>
            <div class="card-body">
                <p>
                    <span class="fa fa-info-circle" style="color:dodgerblue; margin-left:5px; margin-right: 5px; margin-top: 5px;"></span>
                    If the following checkbox is selected, the system will send an email to the appropriate manager when an urgent request is received.
                    <br />
                </p>
                <div class="form-group">
                    @Html.LabelFor(model => model.SmtpSendUrgentEmails, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-10">
                        @Html.CheckBoxFor(model => model.SmtpSendUrgentEmails, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SmtpSendUrgentEmails, "", new { @class = "text-danger" })
                    </div>
                </div>
                <hr />
                <div class="form-group">
                    @Html.LabelFor(model => model.SmtpUrl, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SmtpUrl, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SmtpUrl, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SmtpPort, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SmtpPort, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SmtpPort, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SmtpEmailFrom, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SmtpEmailFrom, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SmtpEmailFrom, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SmtpSenderUsername, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SmtpSenderUsername, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SmtpSenderUsername, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SmtpSenderPassword, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SmtpSenderPassword, new { htmlAttributes = new { @class = "form-control", @value = Model.SmtpSenderPassword} })
                        @Html.ValidationMessageFor(model => model.SmtpSenderPassword, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SmtpShouldUseSsl, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-10">
                        @Html.CheckBoxFor(model => model.SmtpShouldUseSsl, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SmtpShouldUseSsl, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 rounded shadow">
            <h5 class="card-header">Google Maps API</h5>
            <div class="card-body">
                <p>
                    <span class="fa fa-info-circle" style="color:dodgerblue; margin-left:5px; margin-right: 5px; margin-top: 5px;"></span>
                    The Google Maps API Key should be stored here.
                    <br />
                </p>
                <div class="form-group">
                    @Html.LabelFor(model => model.MapsApiKey, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MapsApiKey, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MapsApiKey, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 rounded shadow">
            <h5 class="card-header">Actions</h5>
            <div class="card-body">
                <button type="submit" class="btn btn-success">
                    <i class="fa fa-check"></i>
                    Submit
                </button>
                <button class="btn btn-danger" onclick="location.href = '@Url.Action("Index", "ConfigurationRecord")';return false;">
                    <i class="fa fa-times"></i>
                    Cancel
                </button>
            </div>
        </div>
    </div>
}

FYP_WebApp/Views/ConfigurationRecord/Index.cshtml
@model IEnumerable<FYP_WebApp.Models.ConfigurationRecord>

@{
    ViewBag.Title = "Configuration Records";
}

<h2>Configuration Records</h2>
<hr/>

<p>
    <span class="fa fa-info-circle" style="color:dodgerblue; margin-left:5px; margin-right: 5px; margin-top: 5px;"></span>
    Configuration records hold master fields for the entire system. Only the latest configuration record in a system is used.
</p>

<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StoreLocationAccuracy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MessageOfTheDayText)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StoreLocationAccuracy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MessageOfTheDayText)
            </td>
            <td>
                <button class="btn btn-primary" onclick="location.href = '@Url.Action("Details", "ConfigurationRecord", new {id = item.Id})';return false;">
                    <i class="fa fa-info-circle"></i>
                    View
                </button>
            </td>
        </tr>
    }
</table>
<button class="btn btn-success" onclick="location.href = '@Url.Action("Create", "ConfigurationRecord", new {})';return false;">
    <i class="fa fa-plus-square"></i>
    Create
</button>