FYP_WebApp/Models/ApiLog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using FYP_WebApp.Common_Logic;

namespace FYP_WebApp.Models
{
    public class ApiLog
    {
        public int Id { get; set; }
        [Display(Name = "Log Level")]
        public LogLevel LogLevel { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public DateTime TimeStamp { get; set; }
        [Display(Name = "Request")]
        public string RequestString { get; set; }
        [Display(Name = "Response")]
        public string ResponseString { get; set; }
        [Display(Name = "Status Code")]
        public string StatusCode { get; set; }
        [Display(Name = "Additional Data Fields")]
        public string AdditionalFields { get; set; }
    }
}

FYP_WebApp/Models/ApiLogViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;

namespace FYP_WebApp.Models
{
    public class ApiLogViewModel
    {
        public ApiLog ApiLog { get; set; }
        public List<ApiLogAdditionalField> AdditionalFields { get; set; }
    }
}

FYP_WebApp/Controllers/ApiLogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FYP_WebApp.Common_Logic;
using FYP_WebApp.DataAccessLayer;
using FYP_WebApp.Models;
using FYP_WebApp.ServiceLayer;
using Microsoft.Owin.Security.Facebook;
using Newtonsoft.Json;
using PagedList;

namespace FYP_WebApp.Controllers
{
    [CustomAuth(Roles = "Admin")]
    public class ApiLogController : Controller
    {

        private readonly LogService _logService;

        public ApiLogController()
        {
            _logService = new LogService();
        }

        public ApiLogController(IApiLogRepository apiLogRepository)
        {
            _logService = new LogService(apiLogRepository);
        }

        // GET: ApiLog
        public ActionResult Index(string sortOrder, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSortParameter = sortOrder == "Date" ? "date_desc" : "Date";

            var apiLogs = _logService.GetAllApiLogs();


            switch (sortOrder)
            {
                case "Date":
                    apiLogs = apiLogs.OrderBy(s => s.TimeStamp).ToList();
                    break;
                case "date_desc":
                    apiLogs = apiLogs.OrderByDescending(s => s.TimeStamp).ToList();
                    break;
                default:
                    apiLogs = apiLogs.OrderBy(s => s.Id).ToList();
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            ViewBag.TotalApiCalls = apiLogs.Count;
            ViewBag.TotalApiErrors = apiLogs.Count(x => x.LogLevel == LogLevel.Error);
            ViewBag.TotalApiInfos = apiLogs.Count(x => x.LogLevel == LogLevel.Info);

            return View(apiLogs.ToPagedList(pageNumber, pageSize));
        }

        // GET: ApiLog/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                var apiLog = _logService.GetApiLogDetails(id);
                var additionalFields = _logService.ConvertFieldStringToList(apiLog.AdditionalFields);

                var apiLogViewModel = new ApiLogViewModel {ApiLog = apiLog, AdditionalFields = additionalFields};

                return View(apiLogViewModel);
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new {@Error = Errors.InvalidParameter, @Message = ex.Message});
            }
            catch (ApiLogNotFoundException ex)
            {
                return RedirectToAction("Error", "Error", new { @Error = Errors.EntityNotFound, @Message = ex.Message });

            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _logService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FYP_WebApp/Views/ApiLog/Details.cshtml
@model FYP_WebApp.Models.ApiLogViewModel

@{
    ViewBag.Title = "Details";
}

<head>
    <script src="~/Scripts/highlight.pack.js"></script>
    <link href="~/Content/Highlight/github.css" rel="stylesheet" />
    <script src="~/Scripts/highlightInit.js"></script>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
</head>

<div class="card">
    <div class="card-header">
        API Log
    </div>
    <div class="card-body">
        <div>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.ApiLog.LogLevel)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ApiLog.LogLevel)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ApiLog.TimeStamp)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ApiLog.TimeStamp)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ApiLog.StatusCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ApiLog.StatusCode)
                </dd>

            </dl>
        </div>
    </div>
</div>



<div id="accordion">
    <div class="card bg-light rounded">
        <div class="card-header bg-white" id="headingOne">
            <h5 class="mb-0">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Request
                </button>
            </h5>
        </div>
        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
                <pre>
                   <code>
                        @Html.Raw(Model.ApiLog.RequestString)
                    </code>
                </pre>
            </div>
        </div>
    </div>
    <div class="card bg-light rounded">
        <div class="card-header bg-white" id="headingTwo">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Response
                </button>
            </h5>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body p-0">
                <pre>
                    <code>
                        @Html.Raw(Model.ApiLog.ResponseString)
                    </code>
                </pre>
            </div>
        </div>
    </div>
</div>

@if (Model.AdditionalFields != null)
{
    <div class="card bg-light rounded">
        <div class="card-header bg-white" id="headingTwo">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Additional Fields
                </button>
            </h5>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body p-0">
                <table class="table table-striped">
                    <tr>
                        <th>
                            Data Key
                        </th>
                        <th>
                            Data Value
                        </th>
                    </tr>
                    
                    @foreach (var item in Model.AdditionalFields)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Key)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Value)
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
}

<div class="card rounded shadow mb-3">
    <h5 class="card-header">Actions</h5>
    <div class="card-body">
        <button class="btn btn-primary" onclick="location.href = '@Url.Action("Index", "ApiLog")';return false;">
            <i class="fa fa-times"></i>
            Close Log
        </button>
    </div>
</div>

<script>
    $("pre code").each(function () {
        var html = $(this).html();
        var pattern = html.match(/\s*\n[\t\s]*/);
        $(this).html(html.replace(new RegExp(pattern, "g"), '\n'));
    });
</script>

FYP_WebApp/Views/ApiLog/Index.cshtml
@using System.Data.SqlClient
@using System.Web.UI.WebControls
@using FYP_WebApp.Common_Logic
@model PagedList.IPagedList<FYP_WebApp.Models.ApiLog>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
}

<div class="card-deck mb-5 mt-5">
    <div class="card shadow text-light bg-success">
        <div class="card-body">
            <p>Total API Calls:</p>
            <h1>@ViewBag.TotalApiCalls</h1>
        </div>
    </div>
    
    <div class="card rounded-lg shadow text-light bg-danger">
        <div class="card-body">
            <p>Total API Errors:</p>
            <h1>@ViewBag.TotalApiErrors</h1>
        </div>
    </div>
    
    <div class="card rounded-lg shadow text-light bg-info">
        <div class="card-body">
            <p>Total Info Logs:</p>
            <h1>@ViewBag.TotalApiInfos</h1>
        </div>
    </div>
</div>

<div class="card rounded-lg shadow">
    <h5 class="card-header">API Logs</h5>
    <div class="card-body">
        <table class="table table-hover">
            <tr>
                <th>
                    Log Level
                </th>
                <th>
                    Controller
                </th>
                <th>
                    Action
                </th>
                <th>
                    @Html.ActionLink("Timestamp", "Index", new {SortOrder = ViewBag.DateSortParameter})
                </th>
                <th>
                    Status Code
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr class="@(item.LogLevel == LogLevel.Error ? "table-danger" : null)">
                    <td>
                        @if (item.LogLevel == LogLevel.Warn)
                        {
                            <span class="badge badge-warning">WARN</span>
                        }
                        @if (item.LogLevel == LogLevel.Info)
                        {
                            <span class="badge badge-info">INFO</span>
                        }
                        @if (item.LogLevel == LogLevel.Debug)
                        {
                            <span class="badge badge-dark">DEBUG</span>
                        }
                        @if (item.LogLevel == LogLevel.Error)
                        {
                            <span class="badge badge-danger">ERROR</span>
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Controller)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Action)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TimeStamp)
                    </td>
                    <td>
                        @switch (item.StatusCode)
                        {
                            case "OK":
                                <span class="badge badge-success">OK</span>
                                break;
                            case "Accepted":
                                <span class="badge badge-success">Accepted</span>
                                break;
                            case "NotFound":
                                <span class="badge badge-dark">Not Found</span>
                                break;
                            case "BadRequest":
                                <span class="badge badge-danger">Bad Request</span>
                                break;
                            case "Forbidden":
                                <span class="badge badge-danger">Forbidden</span>
                                break;
                            case "Unauthorized":
                                <span class="badge badge-danger">Unauthorized</span>
                                break;
                            case "Default":
                                <span class="badge badge-warning">@item.StatusCode</span>
                                break;
                        }

                    </td>
                    <td>
                        <button class="btn btn-primary" onclick="location.href = '@Url.Action("Details", "ApiLog", new {id = item.Id})';return false;">
                            <i class="fa fa-search"></i>
                            Inspect
                        </button>
                    </td>
                </tr>
            }
        </table>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("Index", new {page, sortOrder = ViewBag.CurrentSort}))
    </div>
</div>