FYP_WebApp/Models/Pairing.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Foolproof;

namespace FYP_WebApp.Models
{
    public class Pairing
    {
        public int Id { get; set; }
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd H:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime Start { get; set; }
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd H:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime End { get; set; }
        [NotEqualTo("BuddyUserId", ErrorMessage = "Cannot be the same as Buddy User.")]
        [Display(Name = "Team Member")]
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }
        [NotEqualTo("UserId", ErrorMessage = "Cannot be the same as User.")]
        [Display(Name = "Assigned Buddy")]
        public string BuddyUserId { get; set; }
        public ApplicationUser BuddyUser { get; set; }

        public string DisplayString =>
            "[Pairing " + Id + "]: " + Start.Date + " - " + End.Date + " (" + User.Surname + ", " +
            BuddyUser.Surname + ")";
    }
}

FYP_WebApp/Models/PairingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Foolproof;

namespace FYP_WebApp.Models
{
    public class PairingViewModel
    {
        public Pairing Pairing { get; set; }
        public SelectList UserList { get; set; }
        public List<Pairing> ConflictingPairings { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [LessThan("EndDate")]
        public DateTime StartDate { get; set; }
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime StartTime { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [GreaterThan("StartDate")]
        public DateTime EndDate { get; set; }
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime EndTime { get; set; }
    }
}

FYP_WebApp/Controllers/PairingController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Metadata.Edm;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FYP_WebApp.Common_Logic;
using FYP_WebApp.DataAccessLayer;
using FYP_WebApp.Models;
using FYP_WebApp.ServiceLayer;
using Microsoft.AspNet.Identity;

namespace FYP_WebApp.Controllers
{
    public class PairingController : Controller
    {

        private readonly PairingService _pairingService;
        private readonly AccountService _accountService;
        private readonly TeamService _teamService;
        private readonly Library _library;

        public PairingController()
        {
            _pairingService = new PairingService();
            _accountService = new AccountService();
            _teamService = new TeamService();
            _library = new Library();
        }

        public PairingController(IPairingRepository pairingRepository, ApplicationDbContext context, ITeamRepository teamRepository, Library library)
        {
            _pairingService = new PairingService(pairingRepository);
            _accountService = new AccountService(context);
            _teamService = new TeamService(teamRepository);
            _library = library;
        }

        [CustomAuth(Roles = "Admin, Manager")]
        public ActionResult Index()
        {
            var managerId = User.Identity.GetUserId();

            //List<Pairing> visiblePairings = _pairingService.GetAll().Where(x => x.User.TeamId != null && x.User.Team.ManagerId == managerId && x.BuddyUser.TeamId != null && x.BuddyUser.Team.ManagerId == managerId).ToList();

            var visiblePairings = new List<Pairing>();

            var teamMembers = _teamService.GetAllSubordinates(_accountService.GetAll(), managerId);

            foreach (var member in teamMembers)
            {
                foreach (var pairing in _pairingService.GetAll())
                {
                    if (pairing.UserId == member.Id || pairing.BuddyUserId == member.Id)
                    {
                        if (!visiblePairings.Contains(pairing))
                        {
                            visiblePairings.Add(pairing);
                        }
                    }
                }
            }

            if (teamMembers.Count == 0)
            {
                return RedirectToAction("Error", "Error", new { @Error = Errors.InvalidParameter, @Message = "You currently have no team members to pair." });
            }

            return View(visiblePairings);

        }

        [CustomAuth(Roles = "Admin, Manager")]
        public ActionResult Details(int id)
        {
            try
            {
                return View(_pairingService.GetDetails(id));
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new {@Error = Errors.InvalidParameter, @Message = ex.Message});
            }
            catch (PairingNotFoundException ex)
            {
                return RedirectToAction("Error", "Error", new { @Error = Errors.EntityNotFound, @Message = ex.Message });
            }
        }

        [CustomAuth(Roles = "Admin, Manager")]
        public ActionResult Create()
        {
            var userList = new SelectList(_teamService.GetAllSubordinates(_accountService.GetAll().Where(x=> x.IsInactive == false).ToList(), User.Identity.GetUserId()).ToList(), "Id", "DisplayString");
            var pairingViewModel = new PairingViewModel {UserList = userList};
            return View(pairingViewModel);
        }

        [CustomAuth(Roles = "Admin, Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StartDate, StartTime, EndDate, EndTime, Pairing, UserList, ConflictingPairings")] PairingViewModel pairingViewModel)
        {
            var userList = new SelectList(_teamService.GetAllSubordinates(_accountService.GetAll().Where(x => x.IsInactive == false).ToList(), User.Identity.GetUserId()), "Id", "DisplayString");
            pairingViewModel.UserList = userList;

            if (ModelState.IsValid)
            {
                var conflictingPairings = _pairingService.CheckConflictingPairings(pairingViewModel.Pairing);

                if (conflictingPairings != null && conflictingPairings.Count > 0)
                {
                    pairingViewModel.ConflictingPairings = conflictingPairings;
                    return View(pairingViewModel);
                }

                if (pairingViewModel.Pairing == null)
                {
                    return RedirectToAction("Error", "Error", new { @Error = Errors.InvalidParameter, @Message = "No Pairing." });
                }

                pairingViewModel.Pairing.Start =
                    _library.ConstructDateTime(pairingViewModel.StartDate, pairingViewModel.StartTime);
                pairingViewModel.Pairing.End =
                    _library.ConstructDateTime(pairingViewModel.EndDate, pairingViewModel.EndTime);

                var result = _pairingService.Create(pairingViewModel.Pairing);

                if (result.Success)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(pairingViewModel);
                }
            }

            return View(pairingViewModel);
        }

        [CustomAuth(Roles = "Admin, Manager")]
        public ActionResult Edit(int id)
        {
            var userList = new SelectList(_teamService.GetAllSubordinates(_accountService.GetAll().Where(x => x.IsInactive == false).ToList(), User.Identity.GetUserId()), "Id", "DisplayString");

            try
            {
                return View(_pairingService.ConstructViewModel(_pairingService.GetDetails(id), userList));
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new { @Error = Errors.InvalidParameter, @Message = ex.Message });
            }
            catch (PairingNotFoundException ex)
            {
                return RedirectToAction("Error", "Error", new { @Error = Errors.EntityNotFound, @Message = ex.Message });
            }
        }

        [CustomAuth(Roles = "Admin, Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, UserId, BuddyUserId, StartDate, StartTime, EndDate, EndTime, Pairing, UserList, ConflictingPairings")] PairingViewModel pairingViewModel)
        {
            var userList = new SelectList(_teamService.GetAllSubordinates(_accountService.GetAll().Where(x => x.IsInactive == false).ToList(), User.Identity.GetUserId()).ToList(), "Id", "DisplayString");
            pairingViewModel.UserList = userList;

            if (ModelState.IsValid)
            {
                pairingViewModel.Pairing.Start =
                    _library.ConstructDateTime(pairingViewModel.StartDate, pairingViewModel.StartTime);
                pairingViewModel.Pairing.End =
                    _library.ConstructDateTime(pairingViewModel.EndDate, pairingViewModel.EndTime);

                var conflictingPairings = _pairingService.CheckConflictingPairings(pairingViewModel.Pairing);

                if (conflictingPairings != null && conflictingPairings.Count > 0)
                {
                    pairingViewModel.ConflictingPairings = conflictingPairings;
                    return View(pairingViewModel);
                }

                var result = _pairingService.Edit(pairingViewModel.Pairing);

                if (result.Success)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(pairingViewModel);
                }
            }

            return View(pairingViewModel);
        }

        [CustomAuth(Roles = "Admin, Manager")]
        public ActionResult Delete(int id)
        {
            try
            {
                return View(_pairingService.GetDetails(id));
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new { @Error = Errors.InvalidParameter, @Message = ex.Message });
            }
            catch (PairingNotFoundException ex)
            {
                return RedirectToAction("Error", "Error", new { @Error = Errors.EntityNotFound, @Message = ex.Message });
            }
        }

        [CustomAuth(Roles = "Admin, Manager")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pairing pairing = _pairingService.GetDetails(id);

            var result = _pairingService.Delete(pairing);

            if (result.Success)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Error", "Error", new { @Error = Errors.SystemError, @Message = "Unable to delete entity." });
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _pairingService.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

FYP_WebApp/Views/Pairing/Create.cshtml
@model FYP_WebApp.Models.PairingViewModel

@{
    ViewBag.Title = "Create Pairing";
}

<h2>Create Pairing</h2>
<hr/>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @if (Model.ConflictingPairings != null && Model.ConflictingPairings.Count > 0)
        {
            <div class="alert alert-danger" role="alert">
                <h4 class="alert-heading">Important</h4>
                <p>There are already existing pairings for the selected users intersecting with the specified dates.</p>
                <hr>
                <p class="mb-0">Your pairing conflicts with the following existing pairings:</p>
                <div>
                    <ul>
                        @foreach (var pairing in Model.ConflictingPairings)
                        {
                            <li>@pairing.DisplayString</li>
                        }
                    </ul>
                </div>
            </div>
        }
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="card rounded shadow mb-3">
            <h5 class="card-header">Time Information</h5>
            <div class="card-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="card rounded shadow mb-3">
            <h5 class="card-header">Staff</h5>
            <div class="card-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.Pairing.UserId, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Pairing.UserId, (SelectList)Model.UserList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Pairing.UserId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Pairing.BuddyUserId, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Pairing.BuddyUserId, (SelectList)Model.UserList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Pairing.BuddyUserId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="card rounded shadow mb-3">
            <h5 class="card-header">Actions</h5>
            <div class="card-body">
                <div class="form-group">
                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-check"></i>
                        Submit
                    </button>
                    <button type="reset" class="btn btn-warning">
                        <i class="fa fa-sync"></i>
                        Reset
                    </button>
                    <button class="btn btn-danger" onclick="location.href = '@Url.Action("Index", "Pairing")';return false;">
                        <i class="fa fa-times"></i>
                        Cancel
                    </button>
                </div>
            </div>
        </div>
    </div>
}

FYP_WebApp/Views/Pairing/Delete.cshtml
@model FYP_WebApp.Models.Pairing

@{
    ViewBag.Title = "Delete";
}


<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Important!</h4>
    <p>Deleting this record will prevent this pairing from being used for check-ins.</p>
    <hr>
    <p class="mb-0">Are you sure you wish to delete the following record?</p>
    <ul>
        <li>
            <strong>@Html.DisplayNameFor(model => model.Start)</strong> :  @Html.DisplayFor(model => model.Start)
        </li>
        <li>
            <strong> @Html.DisplayNameFor(model => model.End)</strong> :  @Html.DisplayFor(model => model.End)
        </li>
        <li>
            <strong>@Html.DisplayNameFor(model => model.UserId) </strong> : @Html.DisplayFor(model => model.User.DisplayString)
        </li>
        <li>
            <strong> @Html.DisplayNameFor(model => model.BuddyUserId)</strong> :  @Html.DisplayFor(model => model.BuddyUser.DisplayString)
        </li>
    </ul>
</div>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <button class="btn btn-warning" onclick="location.href = '@Url.Action("Details","Pairing", new{id = Model.Id})';return false;">Cancel</button>
    </div>
}

FYP_WebApp/Views/Pairing/Details.cshtml
@using Microsoft.AspNet.Identity
@model FYP_WebApp.Models.Pairing

@{
    ViewBag.Title = "Details";
}

<div class="card rounded shadow mb-3">
    <h5 class="card-header">Pairing @Model.Id (@Model.Start - @Model.End)</h5>
    <div class="card-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Start)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Start)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.End)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.End)
            </dd>

            <dt>
                Team Member
            </dt>

            <dd>
                @Html.DisplayFor(model => model.User.DisplayString)
                @if (Model.UserId == User.Identity.GetUserId())
                {
                    <span class="badge badge-info">You</span>
                }
                else
                {
                    <span class="badge badge-info">@Model.User.Team.Name</span>
                }
            </dd>

            <dt>
               Assigned Buddy
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BuddyUser.DisplayString)
                @if (Model.BuddyUserId == User.Identity.GetUserId())
                {
                    <span class="badge badge-info">You</span>
                }
                else
                {
                    <span class="badge badge-info">@Model.BuddyUser.Team.Name</span>
                }
            </dd>

        </dl>
    </div>
</div>

<div class="card rounded shadow mb-3">
    <h5 class="card-header">Actions</h5>
    <div class="card-body">
        <button class="btn btn-primary" onclick="location.href = '@Url.Action("Index", "Pairing")';return false;">
            <i class="fa fa-arrow-circle-left"></i>
            Back
        </button>
        <button class="btn btn-warning" onclick="location.href = '@Url.Action("Edit", "Pairing", new {id = Model.Id})';return false;">
            <i class="fa fa-edit"></i>
            Edit
        </button>
        <button class="btn btn-danger" onclick="location.href = '@Url.Action("Delete", "Pairing", new {id = Model.Id})';return false;">
            <i class="fa fa-trash"></i>
            Delete
        </button>
    </div>
</div>

FYP_WebApp/Views/Pairing/Edit.cshtml
@model FYP_WebApp.Models.PairingViewModel

@{
    ViewBag.Title = "Edit Pairing";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @if (Model.ConflictingPairings != null && Model.ConflictingPairings.Count > 0)
        {
            <div class="alert alert-danger" role="alert">
                <h4 class="alert-heading">Important</h4>
                <p>There are already existing pairings for the selected users intersecting with the specified dates.</p>
                <hr>
                <p class="mb-0">Your pairing conflicts with the following existing pairings:</p>
                <div>
                    <ul>
                        @foreach (var pairing in Model.ConflictingPairings)
                        {
                            <li>@pairing.DisplayString</li>
                        }
                    </ul>
                </div>
            </div>
        }

        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.Pairing.Id)

        <div class="card rounded shadow mb-3">
            <h5 class="card-header">Time Information</h5>
            <div class="card-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.StartDate, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.StartDate, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.StartDate, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StartTime, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.StartTime, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.StartTime, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EndDate, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EndDate, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.EndDate, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EndTime, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EndTime, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.EndTime, "", new {@class = "text-danger"})
                    </div>
                </div>

            </div>
        </div>

        <div class="card rounded shadow mb-3">
            <h5 class="card-header">Staff</h5>
            <div class="card-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.Pairing.UserId, new {@class = "col-md-2 control-label"})
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Pairing.UserId, (SelectList) Model.UserList, htmlAttributes: new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.Pairing.UserId, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Pairing.BuddyUserId, new {@class = "col-md-2 control-label"})
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Pairing.BuddyUserId, (SelectList) Model.UserList, htmlAttributes: new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.Pairing.BuddyUserId, "", new {@class = "text-danger"})
                    </div>
                </div>
            </div>
        </div>


        <div class="card mb-3 rounded shadow">
            <h5 class="card-header">Actions</h5>
            <div class="card-body">
                <button type="submit" class="btn btn-success">
                    <i class="fa fa-check"></i>
                    Submit
                </button>
                <button class="btn btn-danger" onclick="location.href = '@Url.Action("Details", "Pairing", new {id = Model.Pairing.Id})';return false;">
                    <i class="fa fa-times"></i>
                    Cancel
                </button>
            </div>
        </div>
    </div>

}

FYP_WebApp/Views/Pairing/Index.cshtml
@using System.Runtime.InteropServices
@using Microsoft.AspNet.Identity
@model IEnumerable<FYP_WebApp.Models.Pairing>

@{
    ViewBag.Title = "Subordinate Pairings";
}

<div class="card rounded shadow mb-3">
    <h5 class="card-header">Pairings</h5>
    <div class="card-body">
        <div class="scroller-lg">
            <table class="table table-striped">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Start)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.End)
                    </th>
                    <th>
                        <p>User</p>
                    </th>
                    <th>
                        <p>Buddy</p>
                    </th>
                    <th>
                        <p>Status</p>
                    </th>
                    <th>Actions</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Start)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.End)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.User.DisplayString) 
                            <br/>
                            @if (item.UserId == User.Identity.GetUserId())
                            {
                                <span class="badge badge-info">You</span>
                            }
                            else
                            {
                                <span class="badge badge-info">@item.User.Team.Name</span>
                            }
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BuddyUser.DisplayString)
                            <br/>
                            @if (item.BuddyUserId == User.Identity.GetUserId())
                            {
                                <span class="badge badge-info">You</span>
                            }
                            else
                            {
                                <span class="badge badge-info">@item.BuddyUser.Team.Name</span>
                            }
                        </td>
                        <td>
                            @if (item.End < DateTime.Now)
                            {
                                <span class="badge badge-danger">Expired</span>
                            }
                            @if (item.Start > DateTime.Now)
                            {
                                <span class="badge badge-info">Upcoming</span>
                            }
                            @if (item.Start <= DateTime.Now && item.End >= DateTime.Now)
                            {
                                <span class="badge badge-success">Current</span>
                            }
                        </td>
                        <td>
                            <button class="btn btn-info" onclick="location.href = '@Url.Action("Details", "Pairing", new {id = item.Id})';return false;">
                                <i class="fa fa-eye"></i>
                                View
                            </button>
                        </td>
                    </tr>
                }

            </table>
        </div>
        <button class="btn btn-success" onclick="location.href = '@Url.Action("Create", "Pairing")';return false;">
            <i class="fa fa-plus-square"></i>
            Create
        </button>

    </div>
</div>